import { CaseError } from "../api/case-validation.js";
import { validUploadedObject, MIME_EXTENSIONS } from "../api/upload-validation.js";

export async function archiveCaseFiles(bucket, caseId, files, cleanupKeys) {
  if (!["get", "put", "delete"].every(method => typeof bucket?.[method] === "function")) {
    throw new CaseError(503, "R2_UPLOAD_NOT_CONFIGURED", "Upload service is not configured");
  }
  const archived = [];
  try {
    for (const file of files) {
      // Conditional GET captures exactly the verified B2 object version. A later
      // presigned staging overwrite cannot change this private archived copy.
      const object = await bucket.get(file.key, { onlyIf: { etagMatches: file.etag } });
      if (!object) throw new CaseError(400, "UPLOAD_INCOMPLETE", "One or more uploaded files are missing");
      if (!validUploadedObject(file.key, object)) {
        await object.body?.cancel();
        await cleanPrivateCopies(bucket, [file.key]);
        throw new CaseError(400, "UPLOAD_VALIDATION_FAILED", "One or more uploaded files failed validation");
      }
      if (!object.body || object.etag !== file.etag || object.size !== file.size || object.httpMetadata?.contentType !== file.type) {
        await object.body?.cancel();
        throw new CaseError(409, "UPLOAD_CHANGED", "Upload changed after completion; prepare a new upload");
      }
      const id = crypto.randomUUID();
      const key = `proofs/cases/${caseId}/${id}.${MIME_EXTENSIONS[file.type]}`;
      cleanupKeys.push(key);
      // R2-to-R2 stream only. Browser image bodies still never enter API requests.
      const copy = await bucket.put(key, object.body, { httpMetadata: { contentType: file.type } });
      if (!copy || copy.size !== file.size || !copy.etag) throw new Error("Archive failed");
      archived.push({ id, key, sourceKey: file.key, type: file.type, size: copy.size, etag: copy.etag });
    }
    return archived;
  } catch (error) {
    if (error instanceof CaseError) throw error;
    throw new CaseError(500, "R2_STORAGE_ERROR", "Proof storage is unavailable");
  }
}

export async function cleanPrivateCopies(bucket, keys) {
  // Only keys generated by this request. Never sweep prefixes or other cases.
  const results = await Promise.allSettled(keys.map(key => Promise.resolve().then(() => bucket.delete(key))));
  const failures = results.filter(result => result.status === "rejected").length;
  // Static summary + count only. No exception messages, keys, URL or credentials.
  if (failures) {
    try { console.warn("VoteProof object cleanup incomplete", { failed_count: failures }); }
    catch { /* Logging must not replace the original API error either. */ }
  }
}
